GET http://localhost:3000/records

###
GET http://localhost:3000/user/

###
POST http://localhost:3000/records
Content-Type: application/json


{
  "name": "init"
}

### 
GET http://localhost:3000/records/5f8d48e3a57c7a2924ae0c71

###
PATCH http://localhost:3000/records/5f8d48e3a57c7a2924ae0c71
Content-Type: application/json


{
  "name": "Modified"
}

### 
DELETE  http://localhost:3000/records/5f8d48e3a57c7a2924ae0c71


###

get http://localhost:3000/user/

###

POST http://localhost:3000/user/
Content-Type: application/json

{
  "email": "andrew@email.com",
  "password": "ppp"
}

###
GET http://localhost:3000/user/5f90bc86175391288044a00c

###


PATCH http://localhost:3000/user/5f90bc86175391288044a00c
Content-Type: application/json

{ 
  "password": "katie"
}

###
DELETE http://localhost:3000/user/5f908ef72aaecd26ec5a26e2

###
POST http://localhost:3000/auth/
Content-Type: application/json

{ 
  "email": "andrew@email.com",
  "password": "katie"
}
